In [1]:
# Folio count growth — line chart from 13.26 Cr (Jan 2022) to 26.12 Cr (Dec 2025). Mark key milestones.

In [4]:
import pandas as pd
import plotly.express as px

folio_df = pd.read_csv(
    "../data/raw/06_industry_folio_count.csv",
    parse_dates=["month"]
)

In [5]:
folio_df.head()

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01-01,13.26,9.28,1.86,0.80,1.33
1,2022-04-01,13.91,9.74,1.95,0.83,1.39
2,2022-07-01,13.85,9.69,1.94,0.83,1.38
3,2022-10-01,14.12,9.88,1.98,0.85,1.41
4,2023-01-01,14.81,10.37,2.07,0.89,1.48

In [6]:
folio_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   month                21 non-null     datetime64[us]
 1   total_folios_crore   21 non-null     float64
 2   equity_folios_crore  21 non-null     float64
 3   debt_folios_crore    21 non-null     float64
 4   hybrid_folios_crore  21 non-null     float64
 5   others_folios_crore  21 non-null     float64
dtypes: datetime64[us](1), float64(5)
memory usage: 1.1 KB

In [9]:
folio_df['month_name'] = folio_df['month'].dt.month_name()
folio_df['year'] = folio_df['month'].dt.year

In [10]:
folio_df.head()

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore,month_name,year
0,2022-01-01,13.26,9.28,1.86,0.80,1.33,January,2022
1,2022-04-01,13.91,9.74,1.95,0.83,1.39,April,2022
2,2022-07-01,13.85,9.69,1.94,0.83,1.38,July,2022
3,2022-10-01,14.12,9.88,1.98,0.85,1.41,October,2022
4,2023-01-01,14.81,10.37,2.07,0.89,1.48,January,2023

In [11]:
fig = px.line(
    folio_df,
    x='month',
    y='total_folios_crore',
    title='Folio Count Growth (Jan 2022 - Dec 2025)',
    labels={'month': 'Month', 'total_folios_crore': 'Folio Count (in Crores)'},
)
fig.show()

In [12]:
fig.add_annotation(
    x = folio_df.iloc[0]['month'],
    y = folio_df.iloc[0]['total_folios_crore'],
    text = "Jan 2022: 13.26 Cr",
    showarrow = True,
)

fig.add_annotation(
    x = folio_df.iloc[-1]['month'],
    y = folio_df.iloc[-1]['total_folios_crore'],
    text = "Dec 2025: 26.12 Cr",
    showarrow = True,
)