In [2]:
# Across all mutual funds, which sectors receive the largest investment?"

import pandas as pd
import plotly.express as px

holdings_df = pd.read_csv("../data/raw/09_portfolio_holdings.csv")

In [3]:
holdings_df.head()

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

In [4]:
sector_weights = (holdings_df.groupby('sector')['weight_pct'].sum().reset_index().sort_values(by='weight_pct', ascending=False))

In [5]:
sector_weights.head()

        sector  weight_pct
1      Banking      652.26
7           IT      455.47
11      Pharma      407.45
0   Automobile      323.65
13   Utilities      265.54

In [7]:
fig = px.pie(
    sector_weights,
    values='weight_pct',
    names='sector',
    hole = 0.45,
    title = 'Sector Allocation Across All Mutual Funds'
)
fig.show()

fig.update_traces(textposition='inside', textinfo='percent+label')

fig.show()